# Small Python base image
FROM mcr.microsoft.com/devcontainers/python:3.11

# Upgrade pip and install only Jupyter
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir jupyter
